on:
  rss:
    url:
      - https://github.com/bleedline/aimoneyhunter/commits.atom
      - https://rsshub.app/github/comments/carlrobertoh/CodeGPT
    # config:
    #   limit: 15
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          contentSnippet: ${{on.rss.outputs.contentSnippet}}
          link: ${{on.rss.outputs.link}}
        run: |
          echo title: $title
          echo contentSnippet: $contentSnippet
          echo link: $link
  # pushover-actions:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: pushover-actions
  #       uses: umahmood/pushover-actions@main
  #       env:
  #         PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
  #         PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
  #       with:
  #         title:  ${{on.rss.outputs.title}}
  #         message: ${{on.rss.outputs.contentSnippet}}
  #         url: ${{on.rss.outputs.link}}
  # push-to-ntfy:
  #   name: "Push Ntfy"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Split URL
  #       id: split
  #       run: |
  #         url="${{on.rss.outputs.link}}"
  #         splitedrepo="$(echo $url | awk -F'/' '{print $4" "$5}')"
  #         echo "repo=$splitedrepo" >> $GITHUB_ENV
  #     - name: "Call API"
  #       uses: actionsflow/axios@v1
  #       id: api
  #       with:
  #         url: https://ntfy.sh/lyrl-dev
  #         method: "POST"
  #         body: "Repo:${{env.repo}} ${{on.rss.outputs.title}} ${{on.rss.outputs.contentSnippet}} ${{on.rss.outputs.link}}"
  #     - run: echo ${{ on.rss.outputs }}
  #     - run: echo ${{ steps.api.outputs.status }}
  #     - run: echo ${{ steps.api.outputs.data }}
  #     - run: echo ${{ steps.api.outputs.headers }}
  push-to-telegram:
    name: Push To Telegram
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: "-1002000503194"
          token: "6468152559:AAGDomMcIGJ2FAbkLP5P2xMc71os-OBZmSQ"
          message: |
            ${{on.rss.outputs.title}}
            ${{on.rss.outputs.contentSnippet}}
            link: ${{on.rss.outputs.link}}
