on:
  rss:
    url:
      - https://github.com/1Panel-dev/1Panel/releases.atom
      - https://github.com/actionsflow/actionsflow/releases.atom
      - https://github.com/easychen/aiapi/releases.atom
      - https://github.com/Databingo/aih/releases.atom
      - https://github.com/appsmithorg/appsmith/releases.atom
      - https://github.com/bigcapitalhq/bigcapital/releases.atom
      - https://github.com/IceWhaleTech/CasaOS/releases.atom
      - https://github.com/dgtlmoon/changedetection.io/releases.atom
      - https://github.com/chartbrew/chartbrew/releases.atom
      - https://github.com/Bin-Huang/chatbox/releases.atom
      - https://github.com/lencx/ChatGPT/releases.atom
      - https://github.com/spdustin/ChatGPT-AutoExpert/releases.atom
      - https://github.com/cocktailpeanut/dalai/releases.atom
      - https://github.com/kuafuai/DevOpsGPT/releases.atom
      - https://github.com/veler/DevToys/releases.atom
      - https://github.com/langgenius/dify/releases.atom
      - https://github.com/directus/directus/releases.atom
      - https://github.com/89luca89/distrobox/releases.atom
      - https://github.com/embedchain/embedchain/releases.atom
      - https://github.com/FlowiseAI/Flowise/releases.atom
      - https://github.com/NationalSecurityAgency/ghidra/releases.atom
      - https://github.com/smol-ai/GodMode/releases.atom
      - https://github.com/Pythagora-io/gpt-pilot/releases.atom
      - https://github.com/Z4nzu/hackingtool/releases.atom
      - https://github.com/ajnart/homarr/releases.atom
      - https://github.com/k8sgpt-ai/k8sgpt/releases.atom
      - https://github.com/khoj-ai/khoj/releases.atom
      - https://github.com/ggerganov/llama.cpp/releases.atom
      - https://github.com/metabase/metabase/releases.atom
      - https://github.com/geekan/MetaGPT/releases.atom
      - https://github.com/mindsdb/mindsdb/releases.atom
      - https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/releases.atom
      - https://github.com/nocodb/nocodb/releases.atom
      - https://github.com/binwiederhier/ntfy/releases.atom
      - https://github.com/KillianLucas/open-interpreter/releases.atom
      - https://github.com/openai-translator/openai-translator/releases.atom
      - https://github.com/openchatai/OpenCopilot/releases.atom
      - https://github.com/organicmaps/organicmaps/releases.atom
      - https://github.com/HuolalaTech/page-spy-web/releases.atom
      - https://github.com/tw93/Pake/releases.atom
      - https://github.com/portainer/portainer/releases.atom
      - https://github.com/neulab/prompt2model/releases.atom
      - https://github.com/StanGirard/quivr/releases.atom
      - https://github.com/runtipi/runtipi/releases.atom
      - https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases.atom
      - https://github.com/roboflow/supervision/releases.atom
      - https://github.com/sweepai/sweep/releases.atom
      - https://github.com/ToolJet/ToolJet/releases.atom
      - https://github.com/Danily07/Translumo/releases.atom
      - https://github.com/coqui-ai/TTS/releases.atom
      - https://github.com/neuml/txtai/releases.atom
      - https://github.com/webstudio-is/webstudio/releases.atom
      - https://github.com/meienberger/runtipi/releases.atom
      - https://github.com/SuperDuperDB/superduperdb/releases.atom
      - https://github.com/Codium-ai/pr-agent/releases.atom
      - https://github.com/louislam/uptime-kuma/releases.atom
      - https://github.com/bytebase/bytebase/release.atom
      # PassWall
      - https://github.com/xiaorouji/openwrt-passwall/releases.atom
      - https://github.com/XTLS/Xray-core/releases.atom
      - https://github.com/chaitin/xray/releases.atom
      - https://github.com/fatedier/frp/releases.atom
      - https://github.com/SagerNet/sing-box/releases.atom
      # 
      - https://github.com/Sequel-Ace/Sequel-Ace/releases.atom
      - https://github.com/MichaelYuhe/ai-group-tabs/releases.atom
      - https://github.com/jmorganca/ollama/releases.atom
      - https://github.com/pandora-next/deploy/releases.atom
      - https://github.com/lobehub/lobe-chat/release.atom
    # config:
    #   limit: 15
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          contentSnippet: ${{on.rss.outputs.contentSnippet}}
          link: ${{on.rss.outputs.link}}
        run: |
          echo title: $title
          echo contentSnippet: $contentSnippet
          echo link: $link
  # pushover-actions:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: pushover-actions
  #       uses: umahmood/pushover-actions@main
  #       env:
  #         PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
  #         PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
  #       with:
  #         title:  ${{on.rss.outputs.title}}
  #         message: ${{on.rss.outputs.contentSnippet}}
  #         url: ${{on.rss.outputs.link}}
  push-to-ntfy:
    name: "Push Ntfy"
    runs-on: ubuntu-latest
    steps:
      - name: Split URL
        id: split
        run: |
          url="${{on.rss.outputs.link}}"
          splitedrepo="$(echo $url | awk -F'/' '{print $4" "$5}')"
          echo "repo=$splitedrepo" >> $GITHUB_ENV
      - name: "Call API"
        uses: actionsflow/axios@v1
        id: api
        with:
          url: https://ntfy.sh/lyrl-dev
          method: "POST"
          body: "Repo:${{env.repo}} ${{on.rss.outputs.title}} ${{on.rss.outputs.contentSnippet}} ${{on.rss.outputs.link}}"
      - run: echo ${{ on.rss.outputs }}
      - run: echo ${{ steps.api.outputs.status }}
      - run: echo ${{ steps.api.outputs.data }}
      - run: echo ${{ steps.api.outputs.headers }}
  push-to-telegram:
    name: Push To Telegram
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: "-1002000503194"
          token: "6468152559:AAGDomMcIGJ2FAbkLP5P2xMc71os-OBZmSQ"
          message: |
            ${{on.rss.outputs.title}}
            ${{on.rss.outputs.contentSnippet}}
            link: ${{on.rss.outputs.link}}
